fail_fast: false

repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: make lint
        types: [python]
        language: system
        pass_filenames: false

      - id: mypy
        name: Mypy
        entry: make mypy
        types: [python]
        language: system
        pass_filenames: false
{% if cookiecutter.dockerfile == 'yes' %}

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.9.0
    hooks:
      - id: pip-compile
        name: pip-compile pyproject.toml
        files: ^pyproject.toml$
        args:
          [
            --no-emit-index-url,
            --extra,
            prod,
            --output-file,
            requirements/requirements.txt,
            pyproject.toml,
          ]
{%- endif -%}
