exclude: >
  (?x)^(
  requirements.txt|
  requirements-dev.txt|
  requirements-prod.txt|
  docs|
  .git|
  .eggs|
  .tox
  )

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v0.7.1"
    hooks:
    - id: trailing-whitespace
      files: (^|/)a/.+\.(py|html|sh|css|js)$
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: debug-statements
      language: python
      language_version: python3
    - id: requirements-txt-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.7"
    hooks:
    - id: flake8
      name: flake8
      language: python
      language_version: python3
      files: \.py$
      additional_dependencies: ['flake8-builtins']

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: "v1.0.4"
    hooks:
    - id: python-bandit-vulnerability-check
      args: [--ignore-nosec, -f, screen, -iii, -lll, -x, ./tests, -x, ./.eggs, --recursive, .]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.1.0"
    hooks:
    - id: python-safety-dependencies-check
      language: python

  # seed isort to get consistent behaviour in CI
  - repo: https://github.com/asottile/seed-isort-config
    rev: "v2.1.1"
    hooks:
    - id: seed-isort-config
      language: python

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v4.3.21"
    hooks:
    - id: isort
      language: python

  # Black config
  - repo: https://github.com/ambv/black
    rev: "19.10b0"
    hooks:
    - id: black
