fail_fast: false

repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: make lint
        types: [python]
        language: system
        pass_filenames: false

      - id: mypy
        name: Mypy
        entry: make mypy
        types: [python]
        language: system
        pass_filenames: false
{% if cookiecutter.dockerfile == 'yes' %}

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.1.35
    hooks:
      - id: pip-compile
        name: pip-compile pyproject.toml
        files: ^pyproject.toml$
        args: [pyproject.toml, -o, requirements/requirements.txt]
{%- endif -%}
