exclude: >
  (?x)^(
  docs|
  .git|
  .eggs|
  .tox
  )


repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: "v1.0.4"
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--ignore-nosec, -f, screen, -iii, -lll, -x, ./tests, -x, ./.eggs, --recursive, .]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.1.0"
    hooks:
      - id: python-safety-dependencies-check

  - repo: local  # isort
    hooks:
      - id: isort
        name: isort
        {% if cookiecutter.tool == 'poetry' -%}
        entry: poetry run isort
        {%- else %}
        entry: isort
        {%- endif %}
        args: ["--profile", "black"]
        language: python
        files: \.py$

  - repo: local
    hooks:
      - id: black
        name: black
        {% if cookiecutter.tool == 'poetry' -%}
        entry: poetry run black
        {%- else %}
        entry: black
        {%- endif %}
        language: python
        files: \.py$

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        {% if cookiecutter.tool == 'poetry' -%}
        entry: poetry run flake8
        {%- else %}
        entry: flake8
        {%- endif %}
        language: python
        files: \.py$

  - repo: local  # mypy
    hooks:
      - id: mypy
        name: mypy
        {% if cookiecutter.tool == 'poetry' -%}
        entry: poetry run mypy
        {%- else %}
        entry: mypy
        {%- endif %}
        require_serial: true
        args:
          - "--scripts-are-modules"
          - "--no-incremental"  # do not use the cache
        language: python
        files: \.py$
