language: python

python:
  - 3.6

install:
  - pip install -U pip wheel
  - pip install -U -r requirements-dev.txt
  - pip install .

cache:
  directories:
    - $HOME/.cache/pip

stages:
  - test
  - linter
  - deploy

jobs:
  include:

    - stage: test
      name: "Tests"
      script: pytest --cov-report=term-missing --cov={{ cookiecutter.project_name }}
      after_success:
        - codecov

    - stage: linter
      name: "Linter"
      script: pre-commit run --all-files --show-diff-on-failure

# Let travis-ci CLI tool encrypt your password for PyPI deployment:
# > gem install travis
# > travis encrypt --add deploy.password --com
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}
    python: 3.6
  password:
    secure: "REPLACE ME USING CMDLINE"
