language: python
python:
  - 3.6

install:
  - pip install -r requirements-dev.txt
  - pip install .

jobs:
  include:
    - stage: test
      name: "Tests"
      script: pytest --cov-report=term-missing --cov={{ cookiecutter.project_name }}

    - stage: linter
      name: "Linter"
      script: pre-commit run --all-files --show-diff-on-failure

after_success:
  - codecov

# Let travis-ci CLI tool encrypt your password for PyPI deployment:
# > gem install travis
# > travis encrypt --add deploy.password --com
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: "REPLACE ME USING CMDLINE"
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}
    python: 3.6
