---
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "setup python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      - name: "Install poetry"
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - name: "Build distribution"
        run: |
          source $HOME/.poetry/env && poetry build

      - name: "Publish distribution to PyPI"
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
