---
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "setup python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      {% if cookiecutter.tool == 'poetry' -%}
      - name: "Install and configure Poetry"
        uses: snok/install-poetry@v1.1.6
        with:
          version: 1.2.0a1
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: "Install poetry version plugin"
        run: pip install poetry-dynamic-versioning

      - name: "Build distribution"
        run: poetry-dynamic-versioning && poetry build

      - name: "Publish"
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}
      {%- endif %}
