---
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "setup python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      {%- if cookiecutter.tool == 'poetry' %}
      - name: "Install poetry"
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: "Build distribution"
        run: |
          source $HOME/.poetry/env && poetry build
      {% endif %}

      # - name: "Publish distribution to PyPI"
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: {% raw %}${{ secrets.PYPI_PASSWORD }}{% endraw %}
