---
name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "setup python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      {% if cookiecutter.tool == 'poetry' -%}
      - name: "Install poetry"
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: "Build distribution"
        run: poetry build

      - name: "Publish"
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}
      {%- endif -%}
